# Websites to scrape
WORKUA_URL = "https://work.ua/jobs-python/"
DOUUA_URL = "https://jobs.dou.ua/vacancies/?category=Python"

# Output scraping file path
SCRAPING_OUTPUT_FILE = "scraping/data/jobs.csv"

# Output analysis file path
ANALYSIS_OUTPUT_FILE = "analytics/data/tech_counts.csv"

TECHNOLOGIES_TO_ANALYZE = [
    "python",
    "django",
    "flask",
    "aws",
    "kubernetes",
    "tensorflow",
    "pytorch",
    "sql",
    "postgresql",
    "docker",
    "java",
    "javascript",
    "ruby",
    "react",
    "angular",
    "nodejs",
    "graphql",
    "rest",
    "machine learning",
    "artificial intelligence",
    "data science",
    "devops",
    "agile",
    "scrum",
    "jenkins",
    "c++",
    "go",
    "swift",
    "flutter",
    "vuejs",
    "scala",
    "rust",
    "kotlin",
    "android",
    "ios",
    "spark",
    "hadoop",
    "apache kafka",
    "elasticsearch",
    "mongodb",
    "redis",
    "rabbitmq",
    "microservices",
    "gcp",
    "azure",
    "node.js",
    "typescript",
    "css",
    "html",
    "sql server",
    "laravel",
    "nextjs",
    "nuxtjs",
    "swiftui",
    "flutter",
    "jest",
    "express.js",
    "graphql",
    "firebase",
    "vscode",
    "git",
    "github",
    "bitbucket",
    "azure devops",
    "terraform",
    "ansible",
    "puppet",
    "chef",
    "circleci",
    "travisci",
    "k8s",
    "docker compose",
    "openstack",
    "vagrant",
    "vmware",
    "prometheus",
    "grafana",
    "elasticsearch",
    "logstash",
    "nginx",
    "apache",
    "heroku",
    "docker swarm",
    "jenkins pipelines",
    "cloudformation",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "sklearn",
    "scipy",
    "opengl",
    "sqlite",
    "rust",
    "jupyter",
    "mariadb",
    "flutter",
    "flutterflow",
    "robot framework",
    "spring boot",
    "spring framework",
    "java spring",
    "microservices architecture",
    "oauth",
    "jwt",
    "selenium",
    "puppeteer",
    "kivy",
    "grpc",
    "nestjs",
    "graphql",
    "apollo",
    "redux",
    "material ui",
    "storybook",
    "testcafe",
    "express",
    "meteor",
    "electron",
    "ionic",
    "telerik",
    "jquery",
    "laravel",
    "svelte",
    "tailwind css",
    "vue.js",
    "figma",
    "webpack",
    "parcel",
    "gulp",
    "grunt",
    "babel",
    "es6",
    "webpack dev server",
    "gulpjs",
    "pwa",
    "pm2",
    "mongoos",
    "markdown",
    "sphinx",
    "pytest",
    "php",
    "cakephp",
    "slack",
    "docker hub",
    "apache kafka",
    "graphql subscriptions",
    "pandas",
    "apache spark",
    "ansible tower",
    "kubernetes helm",
    "azure functions",
    "aws lambda",
    "google cloud functions",
    "fargate",
    "rancher",
    "supertest",
    "graphql resolvers",
    "truffle",
    "ipfs",
    "ethereum",
    "blockchain",
    "solidity",
    "web3",
    "nestjs",
    "webpack",
    "webpack plugins",
    "elastic search",
    "neo4j",
    "neo4j cypher",
    "d3.js",
    "three.js",
    "recharts",
    "rxjs",
    "socket.io",
    "flask-restful",
    "fastapi",
    "serverless",
    "express rest api",
    "typescript",
    "react-native",
    "ionic",
    "dart",
    "flutter",
    "docker swarm",
    "elasticsearch",
    "nginx",
    "cloudformation",
    "gce",
    "ecr",
    "docker images",
    "grafana",
    "prometheus",
    "rabbitmq",
    "event-driven architecture",
    "consul",
    "spring boot",
    "spring cloud",
    "rabbitmq",
    "hbase",
    "apache kafka",
    "cloudwatch",
    "mongodb atlas",
    "redis",
    "google kubernetes engine",
    "k8s service mesh",
    "istio",
    "confluent",
    "apache flume",
    "azure kubernetes",
    "k8s ingress",
    "cloud security",
    "bash scripting",
    "bash commands",
    "kotlin",
    "vue",
    "flutter",
    "go lang",
    "cloud foundry",
    "CI/CD",
    "jira",
    "jenkins",
    "gitlab",
    "docker compose",
    "helm charts",
    "apache beam",
    "google data studio",
    "datadog",
    "google analytics",
    "web scraping",
    "scrapy",
    "beautifulsoup",
    "fastapi",
    "uikit",
    "mongodb compass",
    "microfrontends",
    "ssr",
    "nextjs",
    "tailwind",
    "styled components",
    "jest",
    "mocha",
    "chai",
    "chai assertion",
    "selenium webdriver",
    "docker swarm",
    "vagrant",
    "circleci",
    "docker volumes",
    "nginx reverse proxy",
    "kubectl",
    "cloudwatch",
    "aws ec2",
    "jenkins ci",
    "twilio",
    "stripe",
    "sendgrid",
    "firebase",
    "fastlane",
]
